dist: xenial

language: php

php:
  - 7.2

addons:
  mariadb: "10.4"

cache:
  directories:
    - node_modules
    - vendor

before_script:
  - cp .env.travis .env
  - sudo mysql -u root -e 'CREATE DATABASE testing;'
  - sudo mysql -u root -e "CREATE USER 'travis' IDENTIFIED BY 'travis';"
  - sudo mysql -u root -e "GRANT ALL PRIVILEGES ON testing.* TO 'travis'@localhost;"
  - sudo mysql -u root -e 'FLUSH PRIVILEGES;'
  - composer self-update
  - composer install --no-interaction
  - php artisan key:generate
  - php artisan migrate --no-interaction -vvv

script:
  - vendor/bin/phpunit
